### ISSUE TITLE
[Question] Some conflicts caused by toolchains

### ISSUE THREAD

**Issue by morialo3** [ms178/archpkgbuilds#2]
After building `gcc`, and `lib-gcc` then going to installation step, I encounter this error "gcc lib-gcc both contain /usr/share/info/dir.gz" or something similar, also after building `llvm-git` in the installation part, I get this message "libgomp.so
owned by lib-gcc" any suggestion on how to fix/avoid those issues

**Comment by ms178** [comment]
@morialo3 Hm, I haven't seen the first one yet; but I also would discourage to use both my gcc and llvm toolchains at the moment; for GCC, I've seen some test regressions in some projects that I do not see with the default toolchain on CachyOS. For LLVM, the git package does cause headaches with too many other projects, e.g. rust - which is a pain to maintain.

The libgomp.so error sounds familiar though; and I thought to have fixed it in my GCC and/or LLVM-PKGBUILD, if I am not mistaken.

By the way, a highly risky move would be to use `sudo pacman -U --overwrite "*" *.zst --nodeps` to install these packages regardless of these warnings. But I highly discourage this due to the mentioned issues with both. 

If you need a fast LLVM/Clang, I'd rather use the llvm-bolt-scripts to generate such a highly optimized LLVM/Clang but keeping that one in a seperate directory and only use it by calling it up with an environment variable before use (the scripts mention the command and the default directory). This way, you can then use that one for compiling specific packages without having to replace your system LLVM compiler (which has big implications for stability with package updates; Mesa etc.).

P.S: I should warn you that the compile times for such a highly optimized LLVM build are huge, it usually takes 3.5 hours on my 18-Core-Xeon 2696V3 when generating a fresh PGO profile. I only do this once in a while and use the generated PGO profile for subsequent compiles, while this is not optimal for compiler performance, it saves around half of the build time.

**Comment by morialo3** [comment]
>  I've seen some test regressions in some projects that I do not see with the default toolchain on CachyOS

Thanks for the heads-up,  I was trying to cherry-pick for my Archlinux setup.
> By the way, a highly risky move would be to use sudo pacman -U --overwrite "*" *.zst --nodeps to install these packages regardless of these warnings. But I highly discourage this due to the mentioned issues with both.

No worries, always have a backup to roll-back to, just in case I rush things blindly.
> If you need a fast LLVM/Clang, I'd rather use the llvm-bolt-scripts to generate such a highly optimized LLVM/Clang but keeping that one in a seperate directory and only use it by calling it up with an environment variable before use (the scripts mention the command and the default directory). 

I tried to run it, but it gave me an error "Permission denied",  need to check the reason behind this.
> This way, you can then use that one for compiling specific packages without having to replace your system LLVM compiler (which has big implications for stability with package updates; Mesa etc.).

Yeah `mesa` needs a rebuild with every update to the compiler, a bit problematic.
> P.S: I should warn you that the compile times for such a highly optimized LLVM build are huge, it usually takes 3.5 hours on my 18-Core-Xeon 2696V3 when generating a fresh PGO profile. I only do this once in a while and use the generated PGO profile for subsequent compiles, while this is not optimal for compiler performance, it saves around half of the build time.

Never tried `pgo`  since Arch don't have a wiki for it, so I don't know how to set it proper.
Thank you for your reply, very helpful, keep up the good work, and cheers!

**Comment by ms178** [comment]
> > If you need a fast LLVM/Clang, I'd rather use the llvm-bolt-scripts to generate such a highly optimized LLVM/Clang but keeping that one in a seperate directory and only use it by calling it up with an environment variable before use (the scripts mention the command and the default directory).
> 
> I tried to run it, but it gave me an error "Permission denied", need to check the reason behind this.

You need to make these scripts executable first before you can use them: `sudo chmod +x *.bash` 

For a fresh build, you need to rename `build_stage2-prof-use-lto_GENERATE.bash` into `build_stage2-prof-use-lto.bash`  as the first version generates a fresh profile while the other version uses an old profile located in my Download folder (and would error out as you don't have that file - for subsequent runs, you can save the generated profdata, copy it to your download folder and use that other version of the script to save compile time). After a couple of adjustments (you also need to delete the `-fprofile-instr-use=/home/marcus/Downloads/llvm17.profdata` entries in build_stage1 for the same reason), simply execute with `./full_workflow.bash`.

If you want to compile with the saved old profile, you should execute the sub-scripts manually in this order:

setup_llvm_repo.bash
build_stage1.bash
build_stage2-prof-use-lto.bash
build_stage3-bolt-without-sampling.bash

> > P.S: I should warn you that the compile times for such a highly optimized LLVM build are huge, it usually takes 3.5 hours on my 18-Core-Xeon 2696V3 when generating a fresh PGO profile. I only do this once in a while and use the generated PGO profile for subsequent compiles, while this is not optimal for compiler performance, it saves around half of the build time.
> 
> Never tried `pgo` since Arch don't have a wiki for it, so I don't know how to set it proper. Thank you for your reply, very helpful, keep up the good work, and cheers!

The llvm-bolt-scripts do all the neccessary steps automatically if all things go right (that's why it takes so long, as it compiles the compiler multiple times, generates the profile with an instrumented build etc.), but you need all of the dependancies installed first (also jemalloc). Simply use the llvm-git package and makepkg -si to get these and abort the compilation run after the installation of all the dependencies finished.

You might be aware that the whole process puts a lot of strain on the system and its ressources, especially CPU and RAM, 32 GB should do the job when adding `-Wl,--thinlto-jobs=8` to the three `*_LINKER_FLAGS` in the scripts.

**Comment by morialo3** [comment]
Well! thanks alot, I'll definitely try those steps you mentioned above, I might have a question or two about `CFLAGS`  and other flags you use, but leave it for other time. Thanks again, I appreciate your help.
